package util;

import java.util.Vector;

import complex.Complex;

/**
 * Utility class to pass back data generated by user 
 * command execution. Started 6/2015, commands will be 
 * transitioned as necessary to return 'CallPacket's 
 * so the user may have programmatic access to the results.
 * Vectors will often be null or contain single values.
 * @author kens
 */
public class CallPacket {
	public static final int ERROR=-1;
	public static final int INTEGER=1;
	public static final int DOUBLE=2;
	public static final int COMPLEX=3;
	public static final int STRING=4;

	public Vector<Double> double_vec;
	public Vector<Complex> complex_vec;
	public Vector<Integer> int_vec;
	public String strValue;
	public String routineName;
	public boolean error;

	// Constructors
	public CallPacket() {
		routineName=null;
		error=false;
		double_vec=null;
		complex_vec=null;
		int_vec=null;
		strValue=null;
	}
	
	public CallPacket(String rname) {
		this();
		routineName=new String(rname);
	}

}
